[project]
name = "giga-ai-research-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "boto3>=1.42.7",
    "pandas>=2.3.3",
    "pyreadstat>=1.3.2",
]
